spring.application.name=hotelservice-h2
server.port=8082
hotel.code=H2
hotel.name=Grand Hotel Montpellier
hotel.stars=4
hotel.ville=Montpellier
hotel.pays=France
hotel.rue=15 Rue de la Croix d'Or
hotel.numero=666
hotel.latitude=20.8698
hotel.longitude=4.3078
hotel.image-url=http://localhost:8082/images/room2.jpg

spring.datasource.url=jdbc:h2:mem:hotel2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.graphql.graphiql.enabled=true
logging.level.sql=debug
spring.graphql.graphiql.path=/graphiql
logging.level.com.example.hotelservice=INFO
