spring.application.name=agenceservice-a2
server.port=8092

agency.id=AGENCE2
agency.password=secret2
agency.name=VoyagePLUS


hotels[0].name=Grand Hotel Paris
hotels[0].url=http://localhost:8081/graphql

hotels[1].name=Grand Hotel Montpellier
hotels[1].url=http://localhost:8082/graphql
logging.level.com.example.agenceservice=DEBUG
