spring.application.name=agenceservice
server.port=8091

agency.id=AGENCE1
agency.password=secret1
agency.name=Travel2GO

hotels[0].name=Grand Hotel Paris
hotels[0].url=http://localhost:8081/graphql

hotels[1].name=Grand Hotel Montpellier
hotels[1].url=http://localhost:8082/graphql

